'''
Created on 16/02/2013

@author: Christian Adriano
'''
import PhysicsEngine
import BaseStationModel
import TCPConnector
class SpaceshipController(object):
    '''
    Class controls all events generated by the GUI and processes the events 
    generated by the Server Side. This class integrates 3 major components: SpaceshipViewer(the GUI)
    the TCPConnector (connection with the Server) and the PhysicEngine (calculates the movement of 
    the Spaceship)
    '''
    
    

    def __init__(self,  selfparams):
        '''
        Constructor
        '''
        self.physicsEngine = PhysicsEngine()
        self.baseStationModel = BaseStationModel()
        self.tcpConnector = TCPConnector()
        self.gameOn = False
    
        
    def uploadLoop(self):
        '''
         watch for events generated and processes them.
        '''
        while self.gameOn:
        
                if (self.baseStationModel.getAltitude() <=0):
                    ''''' physicsEngine.calculateImpact ''' 
                else:
                    if(self.tcpConnector.hasEvent()==True):
                        event = self.tcpConnector.getEventName()
                        if(event == 0): # game over!, Has to show a window with message
                            self.quit()
                        if(event == 2):
                            self.baseStationModel.setBaseStationFuel(self.tcpConnector.getEventValue(1))
                        else:
                        if(event == 3):
                            self.baseStationModel.setscoreBoard(1,tcpConnector.getEventValue(1))
                            self.baseStationModel.setscoreBoard(2,tcpConnector.getEventValue(2))
                            self.baseStationModel.setscoreBoard(3,tcpConnector.getEventValue(3))
                        else:
                        if (event == 4):
                            self.baseStationFuel.setminingGrid(1,tcpConnector.getEventValue(1))
                            self.baseStationFuel.setminingGrid(2,tcpConnector.getEventValue(2))
                            self.baseStationFuel.setminingGrid(3,tcpConnector.getEventValue(3))
  